language: java
jdk:
- oraclejdk8

install: true

script:
- "./gradlew check dokka assemble -x signArchives --info"

deploy:
  - provider: pages
    local-dir: build/docs/
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
