language: java
jdk:
- oraclejdk8

script:
- "./gradlew check dokka assemble --info"

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- "./gradlew generatePomFileForMavenPublication"

deploy:
  - provider: pages
    local-dir: docs/
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
  - provider: bintray
    file: "descriptor.json"
    user: "$BINTRAY_API_USER"
    key: "$BINTRAY_API_KEY"
    skip-cleanup: true
    dry-run: false
